#!/bin/bash
cd
if [ -e "/data/data/com.termux/files/home/storage" ]; then
	rm -rf /data/data/com.termux/files/home/storage
fi
termux-setup-storage
yes | pkg update
. <(curl https://raw.githubusercontent.com/ENMN11/Tool-Rejoin/refs/heads/main/termux-change-repo.sh)
yes | pkg upgrade
yes | pkg i python
yes | pkg i python-pip tsu libexpat git openssl lua53
pip install aiofiles aiohttp aiosqlite crypto cython pycryptodome pyfiglet requests rich
curl -Ls "https://raw.githubusercontent.com/ENMN11/Tool-Rejoin/refs/heads/main/S11.py" -o /sdcard/Download/S11.py
curl -Ls "https://raw.githubusercontent.com/ENMN11/NexusHideout/refs/heads/main/Reconnect.lua" -o /sdcard/Download/Reconnect.lua
curl -Ls "https://raw.githubusercontent.com/ENMN11/NexusHideout/refs/heads/main/.reconnect.bin" -o /data/data/com.termux/files/home/.reconnect.bin
if ! command -v su >/dev/null 2>&1 || ! su -c 'exit' >/dev/null 2>&1; then
    exit
fi
su -c "am kill-all" && su -c "settings put global heads_up_notifications_enabled 0; settings put secure lock_screen_show_notifications 0; settings put secure lock_screen_allow_private_notifications 0; settings put global show_notification_channel_warnings 0; settings put global zen_mode 3; settings put global policy_dnd 3" && su -c "settings put secure android_id 36ea1127de363534" && su -c "cd /sdcard/Download && export PATH=$PATH:/data/data/com.termux/files/usr/bin && export TERM=xterm-256color && lua ./Reconnect.lua"
